server:
  port: 9093

spring:
  cloud:
    config:

      enabled: false
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: root

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/HRDB
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update